apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:todo-dbs1.database.windows.net,1433;Database=todoapp-db;Uid=admin01;Pwd=admin@123456;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: devopsinsiders/add-task
        ports:
        - containerPort: 8000
